/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_NDKDemo_InvertColor */

#ifndef _Included_com_example_NDKDemo_InvertColor
#define _Included_com_example_NDKDemo_InvertColor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_NDKDemo_InvertColor
 * Method:    executeByC
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_NDKDemo_InvertColor_executeByC
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
